"""
ai/imagery.py — the one place this app generates a picture.

Read the argument before the code, because the scope is the design.

Everything else in this product is traceable. Every figure in a report
carries the digest of the file it came from; every narrative sentence is
checked against the frame before it ships; every chart is deterministic
matplotlib. A generated image traces to nothing. In a deliverable whose
credibility rests on that traceability, a picture that *looks* like
information and carries none is not a feature — it is a liability, and
the damage is not confined to the image: a reader who spots one
plausible-looking generated graphic reasonably discounts everything
next to it.

So the capability exists, and its blast radius is deliberately tiny.

**Where output may go:** the report cover background, and the deck title
slide. Nothing else, ever. Those two surfaces are decoration that is
*known* to be decoration — the cover already paints a flat colour there
— which is exactly why an image with zero information content is
acceptable in that spot and nowhere else.

**What it must never do:** a chart, a table, a plot, a KPI tile, a map,
an org chart, or any diagram that asserts a relationship. Charts stay in
chart_exporter.py and chart_engine.py, deterministic, forever. The
prompt is built from the report *title and theme only* — never from a
column name, a value or a finding — so the image cannot depict the data
even by accident.

**Off by default.** With no model assigned to the `cover_art` task, the
cover renders exactly as it does today. That is not a degraded state; for
most deliverables it is the better one.

**Labelled and recorded, three ways** — with one measured limitation
stated plainly rather than assumed away:

1. A caption on the cover that cannot be turned off. This is the load-
   bearing one. If it were ever removed, the feature should go with it.
2. An entry in the hash-chained audit trail, alongside the numbers.
3. Provenance written into the PNG's own text chunks. This one is
   weaker than it looks: ReportLab re-encodes the image when it embeds
   it, so the chunks are **gone** from an image extracted out of a
   finished PDF — verified, not guessed. It survives only where the
   bytes are handed around directly. Kept because it costs nothing and
   helps on those paths; not counted on for the PDF.

If that seems like a lot of ceremony for a background texture — that is
the correct reaction, and the flat colour is right there.

Free and open-source path: any OpenAI-compatible `/v1/images/generations`
endpoint, which AUTOMATIC1111's OpenAI extension, LocalAI, SD.Next and
ComfyUI wrappers all expose, serving SDXL or FLUX.1-schnell. Local
generation also keeps privacy mode intact — the prompt carries the
client's report title, so cloud generation is refused there like
everything else.
"""
from __future__ import annotations

import hashlib
import io
import logging
from typing import Optional

logger = logging.getLogger(__name__)

#: Shown on every deliverable that carries a generated image. Not
#: configurable, because the whole defence of this feature is that a
#: reader is never in doubt about what they are looking at. If this line
#: is unacceptable in a deliverable, the answer is to leave the task
#: unassigned rather than to remove the line.
CAPTION = ("Cover artwork generated by {model}. Decorative — it contains "
           "no data from this dataset.")

#: Abstract on purpose. A photorealistic warehouse on a warehouse report
#: implies an observation that never happened; a texture implies nothing.
_STYLE = ("Abstract, non-representational background texture suitable for "
          "a corporate report cover. Soft geometric gradients, no text, no "
          "letters, no numbers, no charts, no graphs, no people, no logos, "
          "no recognisable objects. Muted professional palette.")


def is_enabled() -> bool:
    """True only when a model has been assigned to the task."""
    from app.ai import routing
    return bool(routing.resolve_models("cover_art"))


def build_prompt(title: str, domain: str = "") -> str:
    """The prompt, from the title and theme alone.

    Deliberately narrow: the report title is already on the cover, so
    including it leaks nothing that is not printed underneath. A column
    name or a finding would be a different matter, and neither reaches
    this function.
    """
    subject = " ".join(str(title or "Business analysis").split())[:80]
    theme = f" Theme: {domain}." if domain else ""
    return f"{_STYLE} Evoking the subject: {subject}.{theme}"


def generate_cover(title: str, domain: str = "", size: str = "1024x1024",
                   dataset_dir: str = "", actor: str = "") -> Optional[dict]:
    """A cover image, or None if the task has no model assigned.

    Returns the bytes plus the caption and model id the caller must
    display. Never raises: a decorative image failing to generate must
    not cost anyone their report.
    """
    from app.ai import providers, routing

    chain = routing.resolve_models("cover_art")
    if not chain:
        return None

    prompt = build_prompt(title, domain)
    for spec in chain:
        provider = providers.get(spec.provider)
        generate = getattr(provider, "generate_image", None) if provider else None
        if generate is None:
            continue
        try:
            raw = generate(prompt=prompt, size=size, model=spec.model)
        except Exception as e:                     # noqa: BLE001
            logger.warning("[%s] cover art failed: %s", spec.id, e)
            continue
        if not raw:
            continue
        stamped = _stamp(raw, spec.id, prompt)
        result = {
            "image": stamped,
            "model": spec.id,
            "caption": CAPTION.format(model=spec.display),
            "prompt": prompt,
            "sha256": hashlib.sha256(stamped).hexdigest(),
        }
        if dataset_dir:
            _record(dataset_dir, result, actor)
        return result
    return None


def _stamp(data: bytes, model_id: str, prompt: str) -> bytes:
    """Write the provenance into the PNG itself.

    Note what this does *not* achieve: ReportLab re-encodes the image
    when it embeds it, so these chunks do not survive extraction from a
    finished PDF — measured, not assumed. The caption on the cover and
    the audit-trail entry are the labelling that actually holds there.
    This helps only where the bytes travel directly, which is cheap
    enough to be worth having and not enough to rely on.
    """
    try:
        from PIL import Image, PngImagePlugin

        img = Image.open(io.BytesIO(data))
        img.load()
        meta = PngImagePlugin.PngInfo()
        meta.add_text("Analytiq-Generated", "true")
        meta.add_text("Analytiq-Model", model_id)
        meta.add_text("Analytiq-Prompt-SHA256",
                      hashlib.sha256(prompt.encode()).hexdigest())
        meta.add_text("Analytiq-Note",
                      "Decorative artwork. Contains no data.")
        out = io.BytesIO()
        img.save(out, format="PNG", pnginfo=meta)
        return out.getvalue()
    except Exception:                              # noqa: BLE001
        # An unstampable image is still captioned on the page and still
        # recorded in the audit trail, so it is not unlabelled — just
        # less portably labelled.
        logger.warning("could not write provenance into the cover image",
                       exc_info=True)
        return data


def _record(dataset_dir: str, result: dict, actor: str) -> None:
    """Into the same hash-chained trail the numbers get."""
    from app.services import integrity
    integrity.append_audit(
        dataset_dir, "generate", actor=actor, digest=result["sha256"],
        detail={"kind": "cover image", "model": result["model"],
                "placement": "report cover",
                "prompt_sha256": hashlib.sha256(
                    result["prompt"].encode()).hexdigest(),
                "contains_data": False})
