"""
How the report presents itself.

Two rules, both about the same thing — whether the document reads as a
piece of professional work or as something a tool emitted.

1. **Nothing about the tooling appears anywhere.** Not the model, not the
   vendor, not "AI-generated", not on the cover and not in the
   methodology. A reader who sees it discounts every figure above it, and
   for a freelancer delivering this to a client it is the difference
   between a deliverable and a demo.
2. **The methodology reads as a record of decisions a person made**, not
   a feature list. It states what was tested, what was chosen over what,
   and what the analysis will not claim. Where a name belongs, it is the
   analyst's or the firm's — the person accountable for the conclusions.
"""
from __future__ import annotations

import io
import re

import numpy as np
import pandas as pd
import pypdf
import pytest


@pytest.fixture()
def df():
    rng = np.random.default_rng(120)
    n = 300
    return pd.DataFrame({
        "period": pd.date_range("2024-01-01", periods=n, freq="D"),
        "category": rng.choice(["Ops", "Retail", "Trade"], n),
        "revenue": rng.normal(20_000, 3_000, n).round(2),
        "cost": rng.normal(12_000, 2_000, n).round(2),
    })


def _pdf_text(df, domain="finance", **cfg):
    from app.engines.data_profiler import profile_dataset
    from app.engines.pdf_builder import build_pdf
    from app.engines.story_engine import generate_story

    story = generate_story(df)
    config = {"title": "FY24 Review", "subtitle": "", "client_name": "Acme",
              "confidential": True, "theme_name": "", "logo_path": None}
    config.update(cfg)
    pdf = build_pdf(
        df=df, config=config, profile=profile_dataset(df),
        cleaning_summary=None, stats_report=None, bi_report=None,
        ml_report=None, chart_data=[],
        executive_summary=story.executive_summary, findings=story.key_findings,
        risks=story.business_risks, opportunities=story.opportunities,
        recommendations=story.recommended_actions, top_insights=[],
        attrition=None, domain=domain)
    return _flatten(pdf)


def _flatten(pdf: bytes) -> str:
    """Page text with line breaks collapsed.

    A sentence that wraps across two lines is still in the document, and
    an assertion that fails only because of where the line broke is
    testing the layout engine rather than the report.
    """
    text = "\n".join((p.extract_text() or "")
                      for p in pypdf.PdfReader(io.BytesIO(pdf)).pages)
    return re.sub(r"\s+", " ", text)


def _health_text(df, domain="finance", agency="Shweta Analytics"):
    from app.engines.health_engine import build_report_payload, compute_health
    from app.engines.health_pdf_builder import build_health_pdf

    payload = build_report_payload(df, domain)
    pdf = build_health_pdf(
        df, domain, compute_health(df), payload["insights"], "data.csv",
        agency_name=agency,
        executive_summary=payload["executive_summary"],
        key_findings=payload["key_findings"], risks=payload["risks"],
        opportunities=payload["opportunities"], actions=payload["actions"])
    return _flatten(pdf)


# Vendors, model families and the words that give the game away.
_BANNED = (
    "groq", "llama", "gemini", "gemma", "gpt", "openai", "anthropic",
    "claude", "mistral", "qwen", "deepseek", "ollama",
    "ai-generated", "ai generated", "generated by ai", "language model",
    "llm", "chatbot", "prompt", "artificial intelligence",
)


def test_the_main_report_names_no_model_or_vendor(df):
    text = _pdf_text(df).lower()
    for banned in _BANNED:
        assert banned not in text, banned


def test_the_health_report_names_no_model_or_vendor(df):
    text = _health_text(df).lower()
    for banned in _BANNED:
        assert banned not in text, banned


def test_neither_report_calls_itself_automated(df):
    for text in (_pdf_text(df).lower(), _health_text(df).lower()):
        for phrase in ("automatically generated", "auto-generated",
                       "this tool", "the software", "the algorithm decided"):
            assert phrase not in text, phrase


# ══════════════════════════════════════════════════════════
#  The methodology reads as a person's account
# ══════════════════════════════════════════════════════════

def test_the_methodology_states_the_tests_used(df):
    text = _pdf_text(df)
    for expected in ("Shapiro", "Spearman", "Mann-Whitney", "IQR",
                     "Chi-square"):
        assert expected in text, expected


def test_the_methodology_records_judgement_not_just_procedure(df):
    """A list of tests is a feature list. What makes it read as an
    analyst's account is saying what was chosen over what, and why."""
    text = _pdf_text(df)
    assert "Judgement applied" in text
    assert "more conservative was taken" in text


def test_the_methodology_states_what_the_analysis_will_not_claim(df):
    text = _pdf_text(df).lower()
    assert "do not establish causation" in text
    assert "rather than answering it from general expectation" in text


def test_the_methodology_explains_withheld_findings(df):
    """Silence about what was dropped invites the assumption that
    nothing was."""
    text = _pdf_text(df)
    assert "withheld" in text


# ══════════════════════════════════════════════════════════
#  Whose name is on it
# ══════════════════════════════════════════════════════════

def test_the_preparer_is_named_when_given(df):
    text = _pdf_text(df, prepared_by="S. Mishra, Data Analytics")
    assert "S. Mishra, Data Analytics" in text
    assert "responsible for the analysis" in text


def test_no_preparer_line_when_none_is_given(df):
    text = _pdf_text(df)
    assert "responsible for the analysis" not in text


def test_the_client_is_named_in_the_basis_of_preparation(df):
    text = _pdf_text(df)
    assert "Prepared for Acme" in text


def test_the_health_report_carries_the_agency_name(df):
    text = _health_text(df, agency="Shweta Analytics")
    assert "Shweta Analytics" in text


def test_a_preparer_name_with_an_ampersand_does_not_break_the_pdf(df):
    """ReportLab reads the text as mini-HTML; "Shah & Co" would otherwise
    truncate the paragraph at the ampersand."""
    text = _pdf_text(df, prepared_by="Shah & Co Analytics")
    assert "Shah & Co Analytics" in text
